baseurl = ""
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Regina Collins' Blog"
theme = "dream-plus"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "dream-plus"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Regina Collins"
	description = "Just a random blog for random stuff, mostly tech-related."
	avatar = "/images/einstein.png"
	motto = "If you can't explain it clearly, you don't know it well enough."
	enableToc = true
	enableShareCard = true

	favicon = "/img/defaultFav.ico"

  	#Background settings
	enableColorBG= true

	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	#Cards or posts shown per page
	itemsPerPage = 5

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	email = "regcollins@hotmail.com"
	linkedin="regina-collins-25801a8"
	siteStartYear = 2018